create table if not exists public.ai_mechanic_cases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id uuid not null references public.saved_vehicles(id) on delete cascade,
  registration text not null,
  category text not null,
  title text,
  status text not null default 'reserved' check (status in ('reserved','active','closed','failed')),
  credit_cost integer not null default 3 check (credit_cost >= 0),
  openai_response_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_mechanic_messages (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.ai_mechanic_cases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  image_count integer not null default 0 check (image_count between 0 and 3),
  created_at timestamptz not null default now()
);

create index if not exists ai_mechanic_cases_user_created_idx on public.ai_mechanic_cases(user_id, created_at desc);
create index if not exists ai_mechanic_cases_vehicle_idx on public.ai_mechanic_cases(user_id, vehicle_id, created_at desc);
create index if not exists ai_mechanic_messages_case_idx on public.ai_mechanic_messages(case_id, id);

alter table public.ai_mechanic_cases enable row level security;
alter table public.ai_mechanic_messages enable row level security;

drop policy if exists ai_mechanic_cases_select_own on public.ai_mechanic_cases;
create policy ai_mechanic_cases_select_own on public.ai_mechanic_cases for select to authenticated using (user_id = auth.uid());

drop policy if exists ai_mechanic_messages_select_own on public.ai_mechanic_messages;
create policy ai_mechanic_messages_select_own on public.ai_mechanic_messages for select to authenticated using (user_id = auth.uid());

create or replace function public.start_ai_mechanic_case(
  p_vehicle_id uuid,
  p_category text,
  p_issue_text text,
  p_image_count integer default 0
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  v_user_id uuid := auth.uid();
  v_vehicle public.saved_vehicles%rowtype;
  v_profile public.vehicle_profiles%rowtype;
  v_case_id uuid;
  v_credits integer;
  v_cost constant integer := 3;
begin
  if v_user_id is null then raise insufficient_privilege using message='Sign in to use AI Mechanic.'; end if;
  if length(trim(coalesce(p_issue_text,''))) < 3 or length(p_issue_text) > 3000 then raise exception 'Describe the vehicle issue in 3 to 3000 characters.'; end if;
  if coalesce(p_image_count,0) < 0 or coalesce(p_image_count,0) > 3 then raise exception 'Attach up to 3 photos.'; end if;
  if trim(coalesce(p_category,'')) = '' then raise exception 'Choose an issue category.'; end if;

  select * into v_vehicle from public.saved_vehicles where id=p_vehicle_id and user_id=v_user_id;
  if not found then raise exception 'Choose a vehicle from your Garage.'; end if;
  select * into v_profile from public.vehicle_profiles where user_id=v_user_id and registration=v_vehicle.registration;

  insert into private.user_accounts(user_id) values(v_user_id) on conflict(user_id) do nothing;
  perform 1 from private.user_accounts where user_id=v_user_id for update;
  select credits into v_credits from private.user_accounts where user_id=v_user_id;
  if coalesce(v_credits,0) < v_cost then raise exception 'AI Mechanic requires 3 credits to start a diagnosis.'; end if;

  update private.user_accounts set credits=credits-v_cost, updated_at=now() where user_id=v_user_id;
  insert into private.credit_transactions(user_id,amount,reason) values(v_user_id,-v_cost,'ai_mechanic_case');

  insert into public.ai_mechanic_cases(user_id,vehicle_id,registration,category,title,credit_cost)
  values(v_user_id,p_vehicle_id,v_vehicle.registration,left(trim(p_category),80),left(trim(p_issue_text),90),v_cost)
  returning id into v_case_id;

  insert into public.ai_mechanic_messages(case_id,user_id,role,content,image_count)
  values(v_case_id,v_user_id,'user',trim(p_issue_text),coalesce(p_image_count,0));

  return jsonb_build_object(
    'caseId',v_case_id,
    'creditsRemaining',v_credits-v_cost,
    'vehicle',jsonb_build_object(
      'id',v_vehicle.id,'registration',v_vehicle.registration,'make',v_vehicle.make,'model',v_vehicle.model,
      'colour',v_vehicle.colour,'taxStatus',v_vehicle.tax_status,'taxDueDate',v_vehicle.tax_due_date,
      'motStatus',v_vehicle.mot_status,'motExpiryDate',v_vehicle.mot_expiry_date,
      'mileage',coalesce(v_profile.current_mileage,v_vehicle.last_mileage),'nickname',v_profile.nickname,
      'serviceDueDate',v_profile.service_due_date,'serviceDueMileage',v_profile.service_due_mileage
    )
  );
end $$;

create or replace function public.refund_ai_mechanic_case(p_case_id uuid) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_user_id uuid:=auth.uid(); v_case public.ai_mechanic_cases%rowtype;
begin
  if v_user_id is null then raise insufficient_privilege; end if;
  select * into v_case from public.ai_mechanic_cases where id=p_case_id and user_id=v_user_id for update;
  if not found then raise exception 'AI Mechanic case not found.'; end if;
  if v_case.status <> 'reserved' then return jsonb_build_object('refunded',false); end if;
  update private.user_accounts set credits=credits+v_case.credit_cost,updated_at=now() where user_id=v_user_id;
  insert into private.credit_transactions(user_id,amount,reason) values(v_user_id,v_case.credit_cost,'ai_mechanic_refund');
  update public.ai_mechanic_cases set status='failed',updated_at=now() where id=v_case.id;
  return jsonb_build_object('refunded',true);
end $$;

create or replace function public.finalize_ai_mechanic_first_reply(p_case_id uuid,p_assistant_text text,p_response_id text default null) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_user_id uuid:=auth.uid();
begin
  if v_user_id is null then raise insufficient_privilege; end if;
  if length(trim(coalesce(p_assistant_text,''))) < 1 then raise exception 'AI response was empty.'; end if;
  perform 1 from public.ai_mechanic_cases where id=p_case_id and user_id=v_user_id and status='reserved' for update;
  if not found then raise exception 'AI Mechanic case is not available.'; end if;
  insert into public.ai_mechanic_messages(case_id,user_id,role,content) values(p_case_id,v_user_id,'assistant',p_assistant_text);
  update public.ai_mechanic_cases set status='active',openai_response_id=nullif(p_response_id,''),updated_at=now() where id=p_case_id;
  return jsonb_build_object('saved',true);
end $$;

create or replace function public.record_ai_mechanic_exchange(p_case_id uuid,p_user_text text,p_assistant_text text,p_image_count integer default 0,p_response_id text default null) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_user_id uuid:=auth.uid();
begin
  if v_user_id is null then raise insufficient_privilege; end if;
  perform 1 from public.ai_mechanic_cases where id=p_case_id and user_id=v_user_id and status='active' for update;
  if not found then raise exception 'AI Mechanic case is not available.'; end if;
  if length(trim(coalesce(p_user_text,''))) < 1 or length(p_user_text)>3000 then raise exception 'Message is invalid.'; end if;
  if coalesce(p_image_count,0) not between 0 and 3 then raise exception 'Attach up to 3 photos.'; end if;
  insert into public.ai_mechanic_messages(case_id,user_id,role,content,image_count) values(p_case_id,v_user_id,'user',trim(p_user_text),coalesce(p_image_count,0));
  insert into public.ai_mechanic_messages(case_id,user_id,role,content) values(p_case_id,v_user_id,'assistant',p_assistant_text);
  update public.ai_mechanic_cases set openai_response_id=coalesce(nullif(p_response_id,''),openai_response_id),updated_at=now() where id=p_case_id;
  return jsonb_build_object('saved',true);
end $$;

create or replace function public.get_ai_mechanic_case(p_case_id uuid) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_user_id uuid:=auth.uid(); v_case public.ai_mechanic_cases%rowtype; v_vehicle public.saved_vehicles%rowtype; v_profile public.vehicle_profiles%rowtype; v_messages jsonb;
begin
  if v_user_id is null then raise insufficient_privilege; end if;
  select * into v_case from public.ai_mechanic_cases where id=p_case_id and user_id=v_user_id;
  if not found then raise exception 'AI Mechanic case not found.'; end if;
  select * into v_vehicle from public.saved_vehicles where id=v_case.vehicle_id and user_id=v_user_id;
  select * into v_profile from public.vehicle_profiles where user_id=v_user_id and registration=v_vehicle.registration;
  select coalesce(jsonb_agg(jsonb_build_object('role',role,'content',content,'imageCount',image_count,'createdAt',created_at) order by id),'[]'::jsonb) into v_messages from public.ai_mechanic_messages where case_id=v_case.id and user_id=v_user_id;
  return jsonb_build_object('case',jsonb_build_object('id',v_case.id,'category',v_case.category,'title',v_case.title,'status',v_case.status,'createdAt',v_case.created_at,'responseId',v_case.openai_response_id),'vehicle',jsonb_build_object('id',v_vehicle.id,'registration',v_vehicle.registration,'make',v_vehicle.make,'model',v_vehicle.model,'colour',v_vehicle.colour,'taxStatus',v_vehicle.tax_status,'taxDueDate',v_vehicle.tax_due_date,'motStatus',v_vehicle.mot_status,'motExpiryDate',v_vehicle.mot_expiry_date,'mileage',coalesce(v_profile.current_mileage,v_vehicle.last_mileage),'nickname',v_profile.nickname,'serviceDueDate',v_profile.service_due_date,'serviceDueMileage',v_profile.service_due_mileage),'messages',v_messages);
end $$;

create or replace function public.list_ai_mechanic_cases() returns jsonb
language sql security definer set search_path=''
as $$
  select coalesce(jsonb_agg(x order by x->>'createdAt' desc),'[]'::jsonb)
  from (
    select jsonb_build_object('id',c.id,'vehicleId',c.vehicle_id,'registration',c.registration,'category',c.category,'title',c.title,'status',c.status,'createdAt',c.created_at,'updatedAt',c.updated_at) x
    from public.ai_mechanic_cases c where c.user_id=auth.uid() and c.status in ('active','closed') order by c.created_at desc limit 20
  ) s;
$$;

grant execute on function public.start_ai_mechanic_case(uuid,text,text,integer) to authenticated;
grant execute on function public.refund_ai_mechanic_case(uuid) to authenticated;
grant execute on function public.finalize_ai_mechanic_first_reply(uuid,text,text) to authenticated;
grant execute on function public.record_ai_mechanic_exchange(uuid,text,text,integer,text) to authenticated;
grant execute on function public.get_ai_mechanic_case(uuid) to authenticated;
grant execute on function public.list_ai_mechanic_cases() to authenticated;
